/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDaoEventsV2 } from "../IDaoEventsV2";

export class IDaoEventsV2__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDaoEventsV2 {
    return new Contract(address, _abi, signerOrProvider) as IDaoEventsV2;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "eventId",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "bool",
            name: "oneTimeBuy",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "token",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "onsite",
            type: "bool",
          },
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "time",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalQuantity",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalQntySold",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "topic",
            type: "string",
          },
          {
            internalType: "string",
            name: "location",
            type: "string",
          },
          {
            internalType: "string",
            name: "city",
            type: "string",
          },
          {
            internalType: "string",
            name: "ipfsHash",
            type: "string",
          },
          {
            internalType: "bool[]",
            name: "ticketLimited",
            type: "bool[]",
          },
          {
            internalType: "uint256[]",
            name: "tktQnty",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "prices",
            type: "uint256[]",
          },
          {
            internalType: "uint256[]",
            name: "tktQntySold",
            type: "uint256[]",
          },
          {
            internalType: "string[]",
            name: "categories",
            type: "string[]",
          },
        ],
        indexed: false,
        internalType: "struct IDaoEventsV2.Event",
        name: "",
        type: "tuple",
      },
    ],
    name: "CreatedEvent",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "eventId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "seatNo",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "boughtLocation",
            type: "string",
          },
          {
            internalType: "string",
            name: "eventLocation",
            type: "string",
          },
        ],
        indexed: false,
        internalType: "struct IDaoEventsV2.Ticket",
        name: "",
        type: "tuple",
      },
    ],
    name: "SoldTicketDetails1",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "token",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "eventId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "seatNo",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "buyer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "usdtPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "phnxPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "boughtTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalTktsSold",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "categoryTktsSold",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "category",
            type: "string",
          },
        ],
        indexed: false,
        internalType: "struct IDaoEventsV2.SoldTicketStruct",
        name: "",
        type: "tuple",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "SoldTicketDetails2",
    type: "event",
  },
];
