/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { PhoenixAuth } from "../PhoenixAuth";

export class PhoenixAuth__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PhoenixAuth {
    return new Contract(address, _abi, signerOrProvider) as PhoenixAuth;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_challenge",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_partnerId",
        type: "uint256",
      },
    ],
    name: "authenticate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
