/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import { Contract, ContractTransaction } from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDaoEventsV2Interface extends ethers.utils.Interface {
  functions: {};

  events: {
    "CreatedEvent(address,uint256,tuple)": EventFragment;
    "SoldTicketDetails1(tuple)": EventFragment;
    "SoldTicketDetails2(tuple,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatedEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SoldTicketDetails1"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SoldTicketDetails2"): EventFragment;
}

export class IDaoEventsV2 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDaoEventsV2Interface;

  functions: {};

  callStatic: {};

  filters: {
    CreatedEvent(
      owner: string | null,
      eventId: null,
      undefined: null
    ): EventFilter;

    SoldTicketDetails1(undefined: null): EventFilter;

    SoldTicketDetails2(undefined: null, owner: null): EventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
