/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IOracleInterface extends ethers.utils.Interface {
  functions: {
    "fetch(address)": FunctionFragment;
    "fetchPhnxPrice()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "fetch", values: [string]): string;
  encodeFunctionData(
    functionFragment: "fetchPhnxPrice",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "fetch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fetchPhnxPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export class IOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IOracleInterface;

  functions: {
    fetch(token: string, overrides?: Overrides): Promise<ContractTransaction>;

    "fetch(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    fetchPhnxPrice(overrides?: Overrides): Promise<ContractTransaction>;

    "fetchPhnxPrice()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  fetch(token: string, overrides?: Overrides): Promise<ContractTransaction>;

  "fetch(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  fetchPhnxPrice(overrides?: Overrides): Promise<ContractTransaction>;

  "fetchPhnxPrice()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    fetch(token: string, overrides?: CallOverrides): Promise<BigNumber>;

    "fetch(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fetchPhnxPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "fetchPhnxPrice()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    fetch(token: string, overrides?: Overrides): Promise<BigNumber>;

    "fetch(address)"(token: string, overrides?: Overrides): Promise<BigNumber>;

    fetchPhnxPrice(overrides?: Overrides): Promise<BigNumber>;

    "fetchPhnxPrice()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    fetch(token: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "fetch(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    fetchPhnxPrice(overrides?: Overrides): Promise<PopulatedTransaction>;

    "fetchPhnxPrice()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
